### ISSUE TITLE
docs: create PR template

### ISSUE THREAD

**Issue by akebu6** [akebu6/Android-Beginner-Projects#11]
Anyone who can help in creating a PR template that will be used for when someone creates a PR. This will act as a guide to be followed whenever anyone wants to create a PR for this repository

**Comment by gus-lio** [comment]
I can work on a draft of this

**Comment by akebu6** [comment]
> I can work on a draft of this

Thank you for your contribution, the PR has been merged: https://github.com/akebu6/Android-Beginner-Projects/commit/d3d3c0e5414be302224bda88ae74303075f4b474
