### ISSUE TITLE
docs: add contribution guidelines

### ISSUE THREAD

**Issue by akebu6** [akebu6/Android-Beginner-Projects#2]
the repo should have a contributing guideline to help anyone who wants to get started with contributing to the repo

**Comment by Mount-Blanc** [comment]
Hello, I would like to work on this issue. Do you want contributors to make a branch before they PR? or is committing directly to main fine? Any preferred format for PR or git commit messages?

**Comment by akebu6** [comment]
You have a make a new branch and for the commit message it has to follow the following format:

- **Docs**: for documentation
- **Feat**: for adding a new feature
- **Chore**: for mere changes such as spelling etc which won't cause anything you

**Comment by akebu6** [comment]
This issue has been assigned to you
