### ISSUE TITLE
docs: add task manager project to readme

### ISSUE THREAD

**Issue by akebu6** [akebu6/Android-Beginner-Projects#26]
### Project Summary
The project is built using Jetpack Compose, it shows one large checked image indicating that a task has been completed. This is a great beginner project to anyone learning Compose

### To do
1. Fork the repo
2. Clone your fork to your local machine and make the necessary changes to the readme (add a brief description of the project to the readme)
3. Commit your changes (should follow the commit messages standards: feat, chore, docs etc) and
4. finally create a pull request

**Comment by kcoderhtml** [comment]
Do you have any images of the app?

**Comment by akebu6** [comment]
I currently do not have an image but I can send it in a few hours.

**Comment by akebu6** [comment]
This is how it looks like

![Screenshot_20220525-204810.jpg](https://user-images.githubusercontent.com/74776297/170345846-2edb4a32-54b9-419a-bb64-f34f12017a45.jpg)
