### ISSUE TITLE
docs: add tip calculator project to readme

### ISSUE THREAD

**Issue by akebu6** [akebu6/Android-Beginner-Projects#28]

**Comment by kcoderhtml** [comment]
I can do this. Any special instructions or guidelines?

**Comment by akebu6** [comment]
I was meant to add the full description of the issue but here it is:

The tip calculator is used to calculate the amount of tip to be paid to your waiter. It has two fields, one where you enter the total bill and the next where you enter the percentage the customer wishes to pay as a tip. The customer can also choose to round off the tip or to leave it as it is. You can incorporate screenshots. Here is one such screenshot. Just give a brief explanation of what the project is about and you can also read the code to try and understand it
![Screenshot_20220520-204854](https://user-images.githubusercontent.com/74776297/169593439-dd2147b0-4a78-4078-a4cb-a5b6d28db00e.jpg)

**Comment by kcoderhtml** [comment]
Thanks!

**Comment by akebu6** [comment]
No problem, thanks for choosing to work on it!

**Comment by kcoderhtml** [comment]
Does this project use compose or views?

**Comment by akebu6** [comment]
Compose

**Comment by kcoderhtml** [comment]
Thanks!

**Comment by akebu6** [comment]
If you need anymore information please feel free to ask. I may respond instantly or a little later depending on the time

**Comment by kcoderhtml** [comment]
Okay.

**Comment by kcoderhtml** [comment]
I added the Tip Calculator to the Readme and did a few spelling fixes. I also tried to localize the Readme for Spanish but was unable to do so.

**Comment by kcoderhtml** [comment]
Thanks! I enjoyed working on this project!
