### ISSUE TITLE
docs: add description of dice roller app to readme

### ISSUE THREAD

**Issue by akebu6** [akebu6/Android-Beginner-Projects#29]
### Project Summary
The dice roller up is a simple app built using Views. It has a single button which lets the user roll the dice and a large dice image which shows the number that the user has rolled.
You can add a screenshot of the app (you do not need to look at the code or run it. but that will be a added bonus)
For any questions, kindly ask

**Comment by this-Aditya** [comment]
Hey @akebu6 can I contribute to this issue

**Comment by this-Aditya** [comment]
Submitted PR https://github.com/akebu6/Android-Beginner-Projects/issues/29
