### ISSUE TITLE
docs: add compose quadrant project description to readme

### ISSUE THREAD

**Issue by akebu6** [akebu6/Android-Beginner-Projects#30]
### Project Summary
The project is built using Jetpack Compose, it shows the different layouts used in Compose which include: column, row, image and text composables.

### To do
1. Fork the repo
2. Clone your fork to your local machine and make the necessary changes to the readme (add a brief description of the project to the readme)
3. Commit your changes (should follow the commit messages standards: feat, chore, docs etc) and
4. finally create a pull request

**Comment by chadvidovcich** [comment]
Hello @akebu6. Can I work on updating this documentation?

**Comment by akebu6** [comment]
Of course, you are most welcome to. Please feel free to reach out if you have any questions!!!

**Comment by chadvidovcich** [comment]
@akebu6 I have created a pull request for this issue based on the contributing guidelines.

**Comment by akebu6** [comment]
Thank you for your contribution, Your PR has been merged successfully!!! and this issue can be closed
