### ISSUE TITLE
Seekbar in tip calculator

### ISSUE THREAD

**Issue by this-Aditya** [akebu6/Android-Beginner-Projects#52]
in the tip calculator project instead of writing the tip percentage we can also use seekbar which is easy to handle and will be more easy to handle

**Comment by akebu6** [comment]
Hey @this-Aditya , this is a great idea, would you like to work on it?

**Comment by this-Aditya** [comment]
Sure but.. this project is in jetpack compose and I don't know about it.

**Comment by this-Aditya** [comment]
But can i make a project in XML and kotlin file then add a new project to android projects. Which will be helpful for someone who is not aware of jetpack compose

**Comment by akebu6** [comment]
That's a great idea, just remember to update the readme with it. You can make the XML part known in the title but just keep the one done in Compose as well

**Comment by this-Aditya** [comment]
Okay sure ... 
I will be working on it 🙂

**Comment by akebu6** [comment]
Awesome!!
